'use client'
import { useState } from 'react'
type WalletItem={id:string;asset:string;network:string;address:string;note?:string;addressLabel?:string}
const EVM_ADDRESS='0x64afa8201ab478573243a852251d46abe124acd1'
const PRIMARY:WalletItem[]=[{id:'btc',asset:'BTC',network:'Bitcoin',address:'bc1qdzxgxg6qt0sjceercxhfngq47qyr2gyqdpd7tj'},{id:'evm',asset:'ETH · USDT · USDC',network:'Ethereum / ERC-20',address:EVM_ADDRESS,note:'One EVM address for ETH, ERC-20 USDT, and ERC-20 USDC.',addressLabel:'EVM address'}]
const ADDITIONAL:WalletItem[]=[{id:'sol',asset:'SOL',network:'Solana',address:'FsymgjzjxKyEZQeJDuAcDd8fyX7Ny7yxzZX9UKvCzfen'},{id:'bnb',asset:'BNB',network:'BNB Smart Chain / BEP-20',address:EVM_ADDRESS,note:'Uses the EVM address shown in Primary options.',addressLabel:'EVM address'},{id:'doge',asset:'DOGE',network:'Dogecoin',address:'DLThxkLh5skugJnofdm5WRARadX83x4Zmz'},{id:'avax',asset:'AVAX',network:'Avalanche C-Chain',address:EVM_ADDRESS,note:'Uses the EVM address shown in Primary options.',addressLabel:'EVM address'},{id:'xrp',asset:'XRP',network:'XRPL · no destination tag listed',address:'rfNBaSjUQ8r7vCR2aMJKYVG3gNKiQ2Q9uh'}]
async function copyText(text:string){if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return}const el=document.createElement('textarea');el.value=text;el.setAttribute('readonly','');el.style.position='absolute';el.style.left='-9999px';document.body.appendChild(el);el.select();document.execCommand('copy');document.body.removeChild(el)}
function WalletCard({wallet,copied,onCopy}:{wallet:WalletItem;copied:boolean;onCopy:()=>void}){return <article className="support-wallet-card"><div className="support-wallet-top"><div><strong>{wallet.asset}</strong><span>{wallet.network}</span></div><button type="button" onClick={onCopy}>{copied?'Copied':'Copy address'}</button></div>{wallet.note?<p className="support-note">{wallet.note}</p>:null}<span className="address-label">{wallet.addressLabel??'Address'}</span><code className="wallet-address">{wallet.address}</code><p className="support-warning">Verify the asset, chain, and address on your own device before sending. Transfers on the wrong network may be unrecoverable.</p></article>}
export default function SupportWallets(){const [copied,setCopied]=useState<string|null>(null);const render=(wallet:WalletItem)=><WalletCard key={wallet.id} wallet={wallet} copied={copied===wallet.id} onCopy={()=>void copyText(wallet.address).then(()=>{setCopied(wallet.id);window.setTimeout(()=>setCopied(x=>x===wallet.id?null:x),2000)}).catch(()=>setCopied(null))}/>;return <div className="support-wallets"><section><h3 className="support-group-title">Primary options</h3><div className="support-wallet-grid">{PRIMARY.map(render)}</div></section><details className="support-additional"><summary>Additional networks</summary><div className="support-wallet-grid">{ADDITIONAL.map(render)}</div></details></div>}
