import { notFound } from 'next/navigation'
import Link from 'next/link'
import Chip from '../../../components/chip'
import Timeline from '../../../components/timeline'
import EvidenceList from '../../../components/evidence-list'
import { byEntityId,evidenceForProduct,eventsForProduct,productBySlug,products } from '../../../lib/data'
import { salesTone,statusTone,supportTone } from '../../../lib/ui'
export function generateStaticParams(){return products.map(x=>({slug:x.slug}))}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const product=productBySlug(slug);if(!product){notFound();return null}const entity=byEntityId.get(product.entity_id)!;const rows=eventsForProduct(product.id);const sources=evidenceForProduct(product.id);return <article className="page"><p className="eyebrow">Product record · <Link href={`/wallet/${entity.slug}/`}>{entity.canonical_name}</Link></p><div className="title-row"><h1>{product.product_name}</h1><div className="chip-row"><Chip>{product.product_type}</Chip><Chip tone={statusTone(product.status)}>{product.status}</Chip>{product.sales_status?<Chip tone={salesTone(product.sales_status)}>{product.sales_status}</Chip>:null}{product.support_status?<Chip tone={supportTone(product.support_status)}>{product.support_status}</Chip>:null}</div></div><p className="lede">{product.summary}</p><dl className="facts"><div><dt>Launch</dt><dd>{product.launch_date??'—'}</dd></div><div><dt>Sales</dt><dd>{product.sales_status??'—'}</dd></div><div><dt>Support</dt><dd>{product.support_status??'—'}</dd></div><div><dt>Variants</dt><dd>{product.variants?.length?product.variants.join(', '):'—'}</dd></div><div><dt>Confidence</dt><dd>{product.confidence}</dd></div><div><dt>Last verified</dt><dd>{product.last_verified_at}</dd></div></dl><section className="section"><div className="section-heading"><div><p className="kicker">Lifecycle</p><h2>Product timeline</h2></div></div>{rows.length?<Timeline rows={rows}/>:<p className="muted">No product-specific events in the current seed.</p>}</section><section className="section"><div className="section-heading"><div><p className="kicker">Sources</p><h2>Evidence</h2></div></div><EvidenceList rows={sources}/></section></article>}
